import React, { useState } from "react";
import { useMoralis } from "react-moralis";

import {abi} from './CricNFTTeamAgreement.json';
import {
	Flex,
	Box,
	Spacer,
	Heading,
	Button,
	Stack,
	Input,
	NumberInput,
	NumberInputField,
	Image, 
	UnorderedList,
	ListItem,
  Grid,
  Table,
  Tr,
  Td,
} from "@chakra-ui/react";

function Home() {
	const {
		Moralis,
		user,
		logout,
		authenticate,
		enableWeb3,
		isInitialized,
		isAuthenticated,
		isWeb3Enabled,
	} = useMoralis();
	
  //const [iplTeamAddress, setValue] = useState("");
	const [values, setValues] = useState({ iplTeamAddress: ""});

	const setPublishedAddress= async () => {
			let web3 = await Moralis.Web3.enableWeb3();
			let address = "0x31810884311A857c827f8f354c3724f5397FF6b3"				//contract 1
			const contract = new web3.eth.Contract(abi, address.toLowerCase() );
      
      		let iplTeamAddress = "0x7E19A9ce75914769d365EF632fa57CE097D536D2";	////To-do change to dynamically read. Error related to address conversion from UI so hardcoded for now
			let receipt = await contract.methods
			  .setPublishedAddress(iplTeamAddress)
			  .send({ from: user.attributes.ethAddress, value: 0 })
			  .then((response) => console.log(response))
			  .catch((err) => console.log(err));
		  };
	
	return (
		<>
			<Flex sx={{ margin: 3 }}>				
			<Spacer />				
			</Flex>
			
			<Flex sx={{ margin: 3 }} >				
				<Box p="2">
					<Heading size="md">CricNFT is a fully decentralized application to allow any sports to be tokenized.</Heading>
					<h3>This prototype demonstrates</h3> 
					<ol>
						<li>How an 'Indian Premier League' (IPL) team owner can create NFTs in just two simple steps</li> 
						<li>How cricket fans all over the world can be part of their favorite IPL team by minting those NFTs.</li> 
						<li>In addition, the dApp also incentivizes NFT holders of the winning team for that season.</li>
						<li>IPL team owners can collect funds generated by their team’s NFT sale.</li>
						<li>It has its own marketplace to allow easy buying/selling of NFTs by providing interface to Opensea platform.</li>
						</ol>
				</Box>
			<Spacer />
			</Flex>	           
      			         
      <Button style={{backgroundColor: 'black', color:"white", fontFamily:"cursive", width:"200px",height: '30px'}}onClick={setPublishedAddress}>Grant Access</Button>		
		</>
	);
}

export default Home;